* Learn Teach Code, Code Challenges
  Repository for problems and collected solutions for the Learn Teach Code *#code-challenge* slack channel.

  Join the [[https://learnteachcode.herokuapp.com/][Learn Teach Code Slack]] *#code-challenge* channel to get started. Check out the [[https://www.meetup.com/LearnTeachCode][Meetup page]] too.

** How to post a solution
   Post your solution in a way that /doesn't spoil/ for others. Options:

   1. (*Preferred*) As a slack code snippet with 5 blank lines in
      header (Slack folds these automatically)
   2. As a gist/codepen/repl.it/external link
   3. As a pull request into the =solutions= directory of this repo

** Guidelines
   - Use *any language*. Part of the fun is seeing different implementations. But if you want guidance, the community is javascript-oriented, so you might start there.

   - We welcome people at *all levels of skill.* The challenges are designed to be _doable for beginners within reasonable time_, and we want you to participate. The only criterion is time to attempt a solution.

   - The challenges are designed to be *flexible enough for beginner and experienced programmers alike* to have something to chew on. Sharing lots of different approaches and weighing alternatives is the whole point.

   - Healthy discussion of solutions is encouraged. Of course, *be respectful.* People are sharing their work.

   - *Ask questions!* We aren't trying to be tricky, and a benefit of doing challenges in this venue is that we can talk things through. If the prompt isn't clear, or if you need a push in the right direction, feel free to ask. If you get stuck, post a partial solution and ask for help.

   - Try a solution in the bare language first. If the language already implements an identical function, do it by hand. But then: production versions are also welcome, including use of standard library facilities and popular libraries. For instance, if in real life you would use one or two lodash functions in js, or pandas in python, that's an interesting angle to share.

** Challenge List

| *>* | [[file:06_frequentword.org][frequent word]] |           | <2018-12-18 Tue> |
|   5 | [[file:05_collapse.org][collapse]]      |           | [2018-10-22 Mon] |
|   4 | [[file:04_flat.org][flatten]]       | [[file:solutions/04_flat.org][solutions]] | [2018-09-20 Thu] |
|   3 | [[file:03_pairs.org][pair up]]       | [[file:solutions/03_pairs.org][solutions]] | [2018-09-07 Fri] |
|   2 | [[file:02_zip.org][zip]]           | [[file:solutions/02_zip.org][solutions]] | [2018-08-17 Fri] |
|   1 | [[file:01_chessboard.org][chessboard]]    | [[file:solutions/01_chessboard.org][solutions]] | [2018-07-20 Fri] |

*>* current challenge

** License

The contents of this repository are licensed under the [[file:LICENSE][Creative Commons Attribution + Share-alike]] license
